# Generated by Django 4.1.7 on 2023-03-31 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('Gname', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('Pname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Page', models.IntegerField()),
                ('Purl', models.URLField()),
                ('Gname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.games')),
            ],
        ),
    ]
